module.exports.createRequest = function(reqData, xmlOperations, xmlAddresses, xmlContact, xmlAccesses, xmlbuilder) {    
    const xmlRequisicao = 
        xmlbuilder.create('soapenv:Envelope', {version: '1.0', encoding: 'utf-8'})
        .att('xmlns:soapenv', 'http://schemas.xmlsoap.org/soap/envelope/')
        .att('xmlns:ord', 'http://xmlns.oracle.com/communications/ordermanagement')
            .ele('soapenv:Header')
                .ele('wsse:Security')
                .att('soapenv:mustUnderstand', '1')
                .att('xmlns:wsu', 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd')
                .att('xmlns:wsse', 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd')
                    .ele('wsse:UsernameToken')
                    .att('wsu:Id', 'UsernameToken-D67B4B21B543088DD915716705490912')
                        .ele('wsse:Username', 'soa').up()
                        .ele('wsse:Password', 'soati#01')
                        .att('Type', 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText')
                        .up()
                    .up()
                .up()
            .up()
            .ele('soapenv:Body')
                .ele('ord:CreateOrder')
                .att('xmlns:soap-env', 'http://schemas.xmlsoap.org/soap/envelope/')
                .att('xmlns:ns1', 'http://www.oi.net.br/INFRA/SOAFW/SharedResources/Types/v1')
                .att('xmlns:nxsd', 'http://xmlns.oracle.com/pcbpel/nxsd')
                .att('xmlns:im', 'http://xmlns.oracle.com/InputMessage')
                .att('xmlns:msg', 'http://www.oi.net.br/INFRA/SOAFW/SharedResources/Messaging/v2')
                    .ele('_root')
                        .ele('requisicao')
                            .ele(reqData.pedido.name, reqData.pedido.value).up()
                            .ele(reqData.versao.name, reqData.versao.value).up()
                            .ele(reqData.timestamp.name, reqData.timestamp.value).up()
                            .ele(reqData.nomeBundle.name, reqData.nomeBundle.value).up()
                            .ele(reqData.tipoBundle.name, reqData.tipoBundle.value).up()
                            .ele(reqData.tipoPromocao.name, reqData.tipoPromocao.value).up()
                            .ele(reqData.idCatalogo.name, reqData.idCatalogo.value).up()
                            .ele(reqData.codAtividade.name, reqData.codAtividade.value).up()
                            .ele(reqData.origemPedido.name, reqData.origemPedido.value).up()
                            .importDocument(xmlOperations)
                            .importDocument(xmlAddresses)
                            .importDocument(xmlContact)
                            .importDocument(xmlAccesses)
                        .up()
                    .up()
                .up()
            .up()    
        .end({pretty: true});
        
        return xmlRequisicao;
}